const { Schema, model } = require("mongoose");

const postSchema = new Schema({
  postPhotoUrl: {
    type: String,
    default: "https://easterntradelinks.com/front/images/default.png",
  },
  owner: { type: Schema.Types.ObjectId, ref: "User" },
  title: { type: String },
  description: { type: String, required: true, maxlength: 300 },
  tags: {
    type: [String],
    required: false,
    enum: [
      "3D printing",
      "Acting",
      "Air sports",
      "Amateur radio",
      "Archery",
      "Architecture",
      "Astronomy",
      "Backpacking",
      "Baseball",
      "Basketball",
      "Beekeeping",
      "Bird watching",
      "Blacksmithing",
      "Board games",
      "Bodybuilding",
      "Book restoration",
      "Brazilian jiu-jitsu",
      "Cabaret",
      "Calligraphy",
      "Candle making",
      "Coffee roasting",
      "Colouring",
      "Community",
      "Computer programming",
      "Cooking",
      "Cosplaying",
      "Couponing",
      "Creative writing",
      "Crocheting",
      "Cryptography",
      "Cycling",
      "Dance",
      "Digital arts",
      "Do it yourself",
      "Dowsing",
      "Drama",
      "Drawing",
      "Driving",
      "Electronics",
      "Embroidery",
      "Fashion",
      "Fishing",
      "Flower arranging",
      "Flying disc",
      "Flying",
      "Football",
      "Foraging",
      "Foreign language learning",
      "Gambling",
      "Gaming",
      "Gardening",
      "Genealogy",
      "Geocaching",
      "Ghost hunting",
      "Glassblowing",
      "Graffiti",
      "Gunsmithing",
      "Handball",
      "Hiking",
      "Homebrewing",
      "Hooping",
      "Horseback riding",
      "Hunting",
      "Ice skating",
      "Inline skating",
      "Jewelry making",
      "Jigsaw puzzles",
      "Jogging",
      "Juggling",
      "Kabaddi",
      "Kayaking",
      "Kite flying",
      "Kitesurfing",
      "Knapping",
      "Knife making",
      "Knitting",
      "Lacemaking",
      "Lapidary",
      "Larping",
      "Leather crafting",
      "Lego building",
      "Letterboxing",
      "Listening to music",
      "Lockpicking",
      "Machining",
      "Macrame",
      "Magic",
      "Metal detecting",
      "Metalworking",
      "Model building",
      "Motor sports",
      "Mountain biking",
      "Mountaineering",
      "Mushroom hunting",
      "Mycology",
      "Netball",
      "Nordic skating",
      "Orienteering",
      "Origami",
      "Paintball",
      "Painting",
      "Parkour",
      "Pet",
      "Photography",
      "Playing musical instruments",
      "Poi",
      "Polo",
      "Pottery",
      "Puzzles",
      "Quilting",
      "Rafting",
      "Rappelling",
      "Reading",
      "Rock climbing",
      "Role-playing games",
      "Roller skating",
      "Rowing",
      "Rugby",
      "Running",
      "Sailing",
      "Sand art",
      "Scouting",
      "Scrapbook",
      "Scuba diving",
      "Sculling",
      "Sculpting",
      "Sewing",
      "Shooting",
      "Shopping",
      "Singing",
      "Skateboarding",
      "Sketching",
      "Skiing",
      "Skim Boarding",
      "Skydiving",
      "Slacklining",
      "Snowboarding",
      "Soapmaking",
      "Sports",
      "Stand-up comedy",
      "Stone skipping",
      "Sudoku",
      "Surfing",
      "Swimming",
      "Table tennis",
      "Tabletop games",
      "Taekwondo",
      "Tai chi",
      "Taxidermy",
      "Urban exploration",
      "Vacation",
      "Vehicle restoration",
      "Video gaming",
      "Watching movies",
      "Water sports",
      "Web surfing",
      "Whittling",
      "Wood carving",
      "Woodworking",
      "World Building",
      "Writing",
      "Yo-yoing",
      "Yoga",
    ],
  },
  date: {
    type: Date,
    default: () => Date.now(),
  },
});

const Post = model("Post", postSchema);

module.exports = Post;
